name: "estradart"
version: "0.1.5"
documentation: "https://stawa.gitbook.io/estraapi-documentation/"
homepage: "https://github.com/StawaDev/EstraDart"
publish_to: "https://pub.dev"
description: "A Basic Wrapper Anime Image API Using EstraAPI with Dart/Flutter Language"
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  async: ^2.8.2
  http: ^0.13.4