name: "estradart"
version: "0.1.9"
documentation: "https://stawa.gitbook.io/estraapi-documentation/"
homepage: "https://github.com/StawaDev/EstraDart"
description: "A Basic Wrapper Anime Image API with Many Features & User-Friendly Code"
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  async: ^2.8.2
  http: ^0.13.4
  image: ^3.1.1
